---
version: '3'

services:
  logstash-main:
    build: . # Need to add logstash-output-syslog
    volumes:
      - ./etc/logstash/config-main/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./etc/logstash/pipeline-main:/usr/share/logstash/pipeline
      - ./etc/pki:/usr/share/logstash/pki
      - ./logs-out/main:/data/
      - ./pq:/pq
    ports:
      - "10201:10200"
      - "9601:9600"
      - "5000:5000"
  logstash-fb:
    image: docker.elastic.co/logstash/logstash:7.6.2
    volumes:
      - ./etc/logstash/pipeline-fb:/usr/share/logstash/pipeline
      - ./etc/pki:/usr/share/logstash/pki
      - ./logs-out/beats-back:/data/
    environment:
      - XPACK_MONITORING_ENABLED=false
      - PIPELINE_WORKERS=1
    ports:
      - "10202:10200"
      - "9602:9600"
      - "5001:5000"
  logstash-syslog-tcp:
    image: docker.elastic.co/logstash/logstash:7.6.2
    volumes:
      - ./etc/logstash/pipeline-syslog-tcp:/usr/share/logstash/pipeline
      - ./etc/pki:/usr/share/logstash/pki
      - ./logs-out/syslog-tcp-back:/data/
    environment:
      - XPACK_MONITORING_ENABLED=false
      - PIPELINE_WORKERS=1
    ports:
      - "10203:10200"
      - "9603:9600"
      - "5003:5000"
      - "5141:1514"
  logstash-syslog-udp:
    image: docker.elastic.co/logstash/logstash:7.6.2
    volumes:
      # This can use the same config file as the tcp, the setups are identical
      - ./etc/logstash/pipeline-syslog-tcp:/usr/share/logstash/pipeline
      - ./etc/pki:/usr/share/logstash/pki
      - ./logs-out/syslog-udp-back:/data/ # This is the only real diff.
    environment:
      - XPACK_MONITORING_ENABLED=false
      - PIPELINE_WORKERS=1
    ports:
      - "10204:10200"
      - "9604:9600"
      - "5004:5000"
      - "5142:1514"
  filebeat-7:
    image: docker.elastic.co/beats/filebeat:7.7.0
    volumes:
      - ./etc/filebeat7/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./etc/filebeat7/conf.d:/usr/share/filebeat/conf.d
      - ./logs-in:/logs-in/
      - ./etc/pki:/usr/share/logstash/pki
